<a href="https://colab.research.google.com/github/Imshubhham/Imshubham/blob/main/Weather_forcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [73]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [91]:
df = pd.read_csv('/content/Weather Test Data.csv')

In [92]:
df.head()

row ID Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0   Row0   Albury     12.9     25.7       0.0          NaN       NaN   
1   Row1   Albury      9.2     28.0       0.0          NaN       NaN   
2   Row2   Albury     14.3     25.0       0.0          NaN       NaN   
3   Row3   Albury      9.7     31.9       0.0          NaN       NaN   
4   Row4   Albury     15.9     18.6      15.6          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... WindSpeed3pm  Humidity9am  \
0         WSW           46.0          W  ...         26.0         38.0   
1          NE           24.0         SE  ...          9.0         45.0   
2           W           50.0         SW  ...         24.0         49.0   
3         NNW           80.0         SE  ...         28.0         42.0   
4           W           61.0        NNW  ...         28.0         76.0   

   Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0         30.0       1007.6       1008.7       NaN       2.0     21.0   
1         16.0       1017.6       1012.8       NaN       NaN     18.1   
2         19.0       1009.6       1008.2       1.0       NaN     18.1   
3          9.0       1008.9       1003.6       NaN       NaN     18.3   
4         93.0        994.3        993.0       8.0       8.0     17.4   

   Temp3pm  RainToday  
0     23.2         No  
1     26.5         No  
2     24.6         No  
3     30.2         No  
4     15.8        Yes  

[5 rows x 22 columns]

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42677 entries, 0 to 42676
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   row ID         42677 non-null  object 
 1   Location       42677 non-null  object 
 2   MinTemp        42483 non-null  float64
 3   MaxTemp        42585 non-null  float64
 4   Rainfall       42250 non-null  float64
 5   Evaporation    24365 non-null  float64
 6   Sunshine       22178 non-null  float64
 7   WindGustDir    39868 non-null  object 
 8   WindGustSpeed  39887 non-null  float64
 9   WindDir9am     39670 non-null  object 
 10  WindDir3pm     41547 non-null  object 
 11  WindSpeed9am   42264 non-null  float64
 12  WindSpeed3pm   41882 non-null  float64
 13  Humidity9am    42136 non-null  float64
 14  Humidity3pm    41573 non-null  float64
 15  Pressure9am    38411 non-null  float64
 16  Pressure3pm    38432 non-null  float64
 17  Cloud9am       26592 non-null  float64
 18  Cloud3

In [77]:
df.isnull().sum()

row ID               0
Location             0
MinTemp            194
MaxTemp             92
Rainfall           427
Evaporation      18312
Sunshine         20499
WindGustDir       2809
WindGustSpeed     2790
WindDir9am        3007
WindDir3pm        1130
WindSpeed9am       413
WindSpeed3pm       795
Humidity9am        541
Humidity3pm       1104
Pressure9am       4266
Pressure3pm       4245
Cloud9am         16085
Cloud3pm         17092
Temp9am            290
Temp3pm            822
RainToday          427
dtype: int64

In [93]:
df.dropna(subset = ['RainToday'], inplace = True)

In [94]:
df.drop(columns='row ID', inplace=True)

In [80]:
total = df.isnull().sum().sort_values(ascending=False)
percent = ((df.isnull().sum() / df.isnull().count())*100).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data

Total    Percent
Sunshine       20181  47.765680
Evaporation    17967  42.525444
Cloud3pm       16774  39.701775
Cloud9am       15764  37.311243
Pressure9am     4172   9.874556
Pressure3pm     4167   9.862722
WindDir9am      2902   6.868639
WindGustDir     2763   6.539645
WindGustSpeed   2744   6.494675
WindDir3pm      1092   2.584615
Humidity3pm     1066   2.523077
Temp3pm          788   1.865089
WindSpeed3pm     759   1.796450
Humidity9am      462   1.093491
WindSpeed9am     321   0.759763
Temp9am          216   0.511243
MinTemp          136   0.321893
MaxTemp           87   0.205917
Location           0   0.000000
Rainfall           0   0.000000
RainToday          0   0.000000

In [95]:
df['RainToday'] = df['RainToday'].replace({'No': 0, 'Yes': 1})

In [96]:
df['RainToday'].value_counts()

0    32851
1     9399
Name: RainToday, dtype: int64

In [97]:
df.drop('Evaporation', axis = 1, inplace = True)

In [98]:
df.drop('Sunshine', axis = 1, inplace = True)

In [101]:
for col in df.columns:
    if df[col].dtype == 'float64':
        df[col] = df[col].replace({np.nan: np.nanmean(df[col])})
    else:
        pass

In [102]:
df.corr()['RainToday']

<ipython-input-102-3743d0dfd05b>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()['RainToday']


MinTemp          0.051775
MaxTemp         -0.231519
Rainfall         0.504349
WindGustSpeed    0.154481
WindSpeed9am     0.106090
WindSpeed3pm     0.077457
Humidity9am      0.353051
Humidity3pm      0.374107
Pressure9am     -0.184721
Pressure3pm     -0.105664
Cloud9am         0.250485
Cloud3pm         0.224246
Temp9am         -0.100813
Temp3pm         -0.235214
RainToday        1.000000
Name: RainToday, dtype: float64

In [106]:
df.dropna(subset=df.select_dtypes(include='object').columns, inplace=True)

In [107]:
df.isnull().sum()

Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
dtype: int64

In [110]:
df['WindGustDir'].value_counts()

W      2750
SE     2675
S      2588
E      2564
WSW    2550
SSE    2499
N      2460
SSW    2412
SW     2389
ENE    2277
WNW    2230
NW     2209
ESE    2070
NE     1934
NNW    1790
NNE    1709
Name: WindGustDir, dtype: int64

In [114]:
df['WindDir9am'].unique()

array(['W', 'SE', 'SW', 'NNW', 'WNW', 'ENE', 'SSE', 'NE', 'N', 'E', 'ESE',
       'NW', 'NNE', 'S', 'WSW', 'SSW'], dtype=object)

In [115]:
from sklearn.preprocessing import LabelEncoder
categorical_labels = ['W', 'SE', 'SW', 'NNW', 'WNW', 'ENE', 'SSE', 'NE', 'N', 'E', 'ESE', 'NW', 'NNE', 'S', 'WSW', 'SSW']
label_encoder = LabelEncoder()
numeric_labels = label_encoder.fit_transform(categorical_labels)
print("Original labels:", categorical_labels)
print("Numeric labels:", numeric_labels)

Original labels: ['W', 'SE', 'SW', 'NNW', 'WNW', 'ENE', 'SSE', 'NE', 'N', 'E', 'ESE', 'NW', 'NNE', 'S', 'WSW', 'SSW']
Numeric labels: [13  9 12  6 14  1 10  4  3  0  2  7  5  8 15 11]


In [116]:
df['WindGustDir'] = df['WindGustDir'].replace({'W': 13, 'SE': 9, 'SW': 12, 'NNW': 6, 'WNW': 14, 'ENE': 1, 'SSE': 10, 'NE': 4, 'N': 3, 'E': 0, 'ESE': 2, 'NW': 7, 'NNE': 5, 'S': 8, 'WSW': 15, 'SSW': 11})

In [117]:
df['WindDir9am'] = df['WindDir9am'].replace({'W': 13, 'SE': 9, 'SW': 12, 'NNW': 6, 'WNW': 14, 'ENE': 1, 'SSE': 10, 'NE': 4, 'N': 3, 'E': 0, 'ESE': 2, 'NW': 7, 'NNE': 5, 'S': 8, 'WSW': 15, 'SSW': 11})
df['WindDir3pm'] = df['WindDir3pm'].replace({'W': 13, 'SE': 9, 'SW': 12, 'NNW': 6, 'WNW': 14, 'ENE': 1, 'SSE': 10, 'NE': 4, 'N': 3, 'E': 0, 'ESE': 2, 'NW': 7, 'NNE': 5, 'S': 8, 'WSW': 15, 'SSW': 11})

In [120]:
df.drop('Location', inplace = True, axis = 1)

In [121]:
df.head()

MinTemp  MaxTemp  Rainfall  WindGustDir  WindGustSpeed  WindDir9am  \
0     12.9     25.7       0.0           15           46.0          13   
1      9.2     28.0       0.0            4           24.0           9   
2     14.3     25.0       0.0           13           50.0          12   
3      9.7     31.9       0.0            6           80.0           9   
4     15.9     18.6      15.6           13           61.0           6   

   WindDir3pm  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
0          15          19.0          26.0         38.0         30.0   
1           0          11.0           9.0         45.0         16.0   
2          13          20.0          24.0         49.0         19.0   
3           7           7.0          28.0         42.0          9.0   
4           6          28.0          28.0         76.0         93.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  
0       1007.6       1008.7  4.405006  2.000000     21.0     23.2          0  
1       1017.6       1012.8  4.405006  4.462514     18.1     26.5          0  
2       1009.6       1008.2  1.000000  4.462514     18.1     24.6          0  
3       1008.9       1003.6  4.405006  4.462514     18.3     30.2          0  
4        994.3        993.0  8.000000  8.000000     17.4     15.8          1

In [122]:
X = df.drop('RainToday', axis = 1)
y = df['RainToday']

In [123]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [124]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [127]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred)*100)
print(confusion_matrix(y_test, y_pred))

88.20517427236794
[[8399  187]
 [1126 1420]]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [128]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred)*100)
print(confusion_matrix(y_test, y_pred))

100.0
[[8586    0]
 [   0 2546]]


In [129]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred)*100)
print(confusion_matrix(y_test, y_pred))

100.0
[[8586    0]
 [   0 2546]]


In [130]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred)*100)
print(confusion_matrix(y_test, y_pred))

96.05641394178943
[[8148  438]
 [   1 2545]]
