<a href="https://colab.research.google.com/github/Imshubhham/Imshubham/blob/main/Weather_forcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df1 = pd.read_csv('/content/Weather Test Data.csv')
df2 = pd.read_csv('/content/Weather Training Data.csv')

In [ ]:
df = pd.concat([df1, df2], ignore_index=True)

In [ ]:
df.head()

row ID Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0   Row0   Albury     12.9     25.7       0.0          NaN       NaN   
1   Row1   Albury      9.2     28.0       0.0          NaN       NaN   
2   Row2   Albury     14.3     25.0       0.0          NaN       NaN   
3   Row3   Albury      9.7     31.9       0.0          NaN       NaN   
4   Row4   Albury     15.9     18.6      15.6          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0         WSW           46.0          W  ...        38.0         30.0   
1          NE           24.0         SE  ...        45.0         16.0   
2           W           50.0         SW  ...        49.0         19.0   
3         NNW           80.0         SE  ...        42.0          9.0   
4           W           61.0        NNW  ...        76.0         93.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
1       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
2       1009.6       1008.2       1.0       NaN     18.1     24.6         No   
3       1008.9       1003.6       NaN       NaN     18.3     30.2         No   
4        994.3        993.0       8.0       8.0     17.4     15.8        Yes   

   RainTomorrow  
0           NaN  
1           NaN  
2           NaN  
3           NaN  
4           NaN  

[5 rows x 23 columns]

In [ ]:
df.columns

Index(['row ID', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [ ]:
df.shape

(142193, 23)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142193 entries, 0 to 142192
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   row ID         142193 non-null  object 
 1   Location       142193 non-null  object 
 2   MinTemp        141556 non-null  float64
 3   MaxTemp        141871 non-null  float64
 4   Rainfall       140787 non-null  float64
 5   Evaporation    81350 non-null   float64
 6   Sunshine       74377 non-null   float64
 7   WindGustDir    132863 non-null  object 
 8   WindGustSpeed  132923 non-null  float64
 9   WindDir9am     132180 non-null  object 
 10  WindDir3pm     138415 non-null  object 
 11  WindSpeed9am   140845 non-null  float64
 12  WindSpeed3pm   139563 non-null  float64
 13  Humidity9am    140419 non-null  float64
 14  Humidity3pm    138583 non-null  float64
 15  Pressure9am    128179 non-null  float64
 16  Pressure3pm    128212 non-null  float64
 17  Cloud9am       88536 non-null

In [ ]:
df.isnull().sum()

row ID               0
Location             0
MinTemp            637
MaxTemp            322
Rainfall          1406
Evaporation      60843
Sunshine         67816
WindGustDir       9330
WindGustSpeed     9270
WindDir9am       10013
WindDir3pm        3778
WindSpeed9am      1348
WindSpeed3pm      2630
Humidity9am       1774
Humidity3pm       3610
Pressure9am      14014
Pressure3pm      13981
Cloud9am         53657
Cloud3pm         57094
Temp9am            904
Temp3pm           2726
RainToday         1406
RainTomorrow     42677
dtype: int64

In [ ]:
df.dropna(subset=['RainTomorrow'], inplace=True)

In [ ]:
df.dropna(subset = ['RainToday'], inplace = True)

In [ ]:
df['RainTomorrow'].value_counts()

0.0    77157
1.0    22359
Name: RainTomorrow, dtype: int64

In [ ]:
df.drop(columns='row ID', inplace=True)

In [ ]:
df.head()

Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
42677   Albury     13.4     22.9       0.6          NaN       NaN           W   
42678   Albury      7.4     25.1       0.0          NaN       NaN         WNW   
42679   Albury     17.5     32.3       1.0          NaN       NaN           W   
42680   Albury     14.6     29.7       0.2          NaN       NaN         WNW   
42681   Albury      7.7     26.7       0.0          NaN       NaN           W   

       WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
42677           44.0          W        WNW  ...         71.0         22.0   
42678           44.0        NNW        WSW  ...         44.0         25.0   
42679           41.0        ENE         NW  ...         82.0         33.0   
42680           56.0          W          W  ...         55.0         23.0   
42681           35.0        SSE          W  ...         48.0         19.0   

       Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
42677       1007.7       1007.1       8.0       NaN     16.9     21.8   
42678       1010.6       1007.8       NaN       NaN     17.2     24.3   
42679       1010.8       1006.0       7.0       8.0     17.8     29.7   
42680       1009.2       1005.4       NaN       NaN     20.6     28.9   
42681       1013.4       1010.1       NaN       NaN     16.3     25.5   

       RainToday  RainTomorrow  
42677         No           0.0  
42678         No           0.0  
42679         No           0.0  
42680         No           0.0  
42681         No           0.0  

[5 rows x 22 columns]

In [ ]:
df.shape

(98537, 22)

In [ ]:
total = df.isnull().sum().sort_values(ascending=False)
percent = ((df.isnull().sum() / df.isnull().count())*100).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data

Total    Percent
Sunshine       46624  47.316237
Evaporation    41727  42.346530
Cloud3pm       39320  39.903792
Cloud9am       36861  37.408283
Pressure3pm     9602   9.744563
Pressure9am     9571   9.713103
WindDir9am      6758   6.858337
WindGustDir     6400   6.495022
WindGustSpeed   6361   6.455443
WindDir3pm      2578   2.616276
Humidity3pm     2435   2.471153
Temp3pm         1836   1.863259
WindSpeed3pm    1772   1.798309
Humidity9am     1055   1.070664
WindSpeed9am     734   0.744898
Temp9am          440   0.446533
MinTemp          332   0.336929
MaxTemp          220   0.223266
RainToday          0   0.000000
Location           0   0.000000
Rainfall           0   0.000000
RainTomorrow       0   0.000000

In [ ]:
df['RainToday'] = df['RainToday'].replace({'No': 0, 'Yes': 1})

In [ ]:
df['RainToday'].value_counts()

0    76481
1    22056
Name: RainToday, dtype: int64

In [ ]:
df.drop('Evaporation', axis = 1, inplace = True)

In [ ]:
df.drop('Sunshine', axis = 1, inplace = True)

In [ ]:
for col in df.columns:
    if df[col].dtype == 'float64':
        df[col] = df[col].replace({np.nan: np.nanmean(df[col])})
    else:
        pass

In [ ]:
df.corr()['RainToday']

<ipython-input-318-3743d0dfd05b>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()['RainToday']


MinTemp          0.057964
MaxTemp         -0.227410
Rainfall         0.499579
WindGustSpeed    0.147779
WindSpeed9am     0.100088
WindSpeed3pm     0.080051
Humidity9am      0.350153
Humidity3pm      0.373257
Pressure9am     -0.178522
Pressure3pm     -0.099037
Cloud9am         0.245422
Cloud3pm         0.211746
Temp9am         -0.094355
Temp3pm         -0.231305
RainToday        1.000000
RainTomorrow     0.311751
Name: RainToday, dtype: float64

In [ ]:
df.dropna(subset=df.select_dtypes(include='object').columns, inplace=True)

In [ ]:
df.isnull().sum()

Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RainTomorrow     0
dtype: int64

In [ ]:
df['WindGustDir'].value_counts()

W      6427
SE     6133
SSE    5987
E      5940
SW     5826
S      5820
N      5781
WSW    5749
SSW    5661
WNW    5239
ENE    5174
NW     5154
ESE    4756
NE     4552
NNE    4220
NNW    4185
Name: WindGustDir, dtype: int64

In [ ]:
df['WindDir9am'].unique()

array(['W', 'NNW', 'ENE', 'SSE', 'S', 'NE', 'SSW', 'N', 'WSW', 'SE',
       'ESE', 'E', 'NW', 'NNE', 'SW', 'WNW'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
categorical_labels = ['W', 'SE', 'SW', 'NNW', 'WNW', 'ENE', 'SSE', 'NE', 'N', 'E', 'ESE', 'NW', 'NNE', 'S', 'WSW', 'SSW']
label_encoder = LabelEncoder()
numeric_labels = label_encoder.fit_transform(categorical_labels)
print("Original labels:", categorical_labels)
print("Numeric labels:", numeric_labels)

Original labels: ['W', 'SE', 'SW', 'NNW', 'WNW', 'ENE', 'SSE', 'NE', 'N', 'E', 'ESE', 'NW', 'NNE', 'S', 'WSW', 'SSW']
Numeric labels: [13  9 12  6 14  1 10  4  3  0  2  7  5  8 15 11]


In [ ]:
df['WindGustDir'] = df['WindGustDir'].replace({'W': 13, 'SE': 9, 'SW': 12, 'NNW': 6, 'WNW': 14, 'ENE': 1, 'SSE': 10, 'NE': 4, 'N': 3, 'E': 0, 'ESE': 2, 'NW': 7, 'NNE': 5, 'S': 8, 'WSW': 15, 'SSW': 11})

In [ ]:
df['WindDir9am'] = df['WindDir9am'].replace({'W': 13, 'SE': 9, 'SW': 12, 'NNW': 6, 'WNW': 14, 'ENE': 1, 'SSE': 10, 'NE': 4, 'N': 3, 'E': 0, 'ESE': 2, 'NW': 7, 'NNE': 5, 'S': 8, 'WSW': 15, 'SSW': 11})
df['WindDir3pm'] = df['WindDir3pm'].replace({'W': 13, 'SE': 9, 'SW': 12, 'NNW': 6, 'WNW': 14, 'ENE': 1, 'SSE': 10, 'NE': 4, 'N': 3, 'E': 0, 'ESE': 2, 'NW': 7, 'NNE': 5, 'S': 8, 'WSW': 15, 'SSW': 11})

In [ ]:
df.drop('Location', inplace = True, axis = 1)

In [ ]:
df.head()

MinTemp  MaxTemp  Rainfall  WindGustDir  WindGustSpeed  WindDir9am  \
42677     13.4     22.9       0.6           13           44.0          13   
42678      7.4     25.1       0.0           14           44.0           6   
42679     17.5     32.3       1.0           13           41.0           1   
42680     14.6     29.7       0.2           14           56.0          13   
42681      7.7     26.7       0.0           13           35.0          10   

       WindDir3pm  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
42677          14          20.0          24.0         71.0         22.0   
42678          15           4.0          22.0         44.0         25.0   
42679           7           7.0          20.0         82.0         33.0   
42680          13          19.0          24.0         55.0         23.0   
42681          13           6.0          17.0         48.0         19.0   

       Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
42677       1007.7       1007.1  8.000000  4.515055     16.9     21.8   
42678       1010.6       1007.8  4.442393  4.515055     17.2     24.3   
42679       1010.8       1006.0  7.000000  8.000000     17.8     29.7   
42680       1009.2       1005.4  4.442393  4.515055     20.6     28.9   
42681       1013.4       1010.1  4.442393  4.515055     16.3     25.5   

       RainToday  RainTomorrow  
42677          0           0.0  
42678          0           0.0  
42679          0           0.0  
42680          0           0.0  
42681          0           0.0

In [ ]:
X = df.drop('RainToday', axis = 1)
y = df['RainToday']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred)*100)
print(confusion_matrix(y_test, y_pred))

89.19251789700562
[[19707   490]
 [ 2318  3467]]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred)*100)
print(confusion_matrix(y_test, y_pred))

100.0
[[20197     0]
 [    0  5785]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred)*100)
print(confusion_matrix(y_test, y_pred))

99.98845354476175
[[20197     0]
 [    3  5782]]


In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred)*100)
print(confusion_matrix(y_test, y_pred))

95.1004541605727
[[18925  1272]
 [    1  5784]]
